[project]
name = "capiba-odonto-ufrpe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bruno Marques", email = "brunomdsv5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
capiba-odonto-ufrpe = "capiba_odonto_ufrpe:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
